### ISSUE TITLE
Login Page issue

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem#5]
It would be preferable if hello student was displayed instead of hello, friend!
![Screenshot 2021-04-09 231912](https://user-images.githubusercontent.com/80934693/114303372-90ab3c80-9aed-11eb-828b-d3f19042f16d.png)

**Comment by sumitkaji** [comment]
instead of hello friend it is corrected to SignUp
![Screenshot (160)](https://user-images.githubusercontent.com/81735853/114979390-851f9300-9eaa-11eb-8487-02ba7b6916be.png)
