### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem#6]
As an administrator 
I want  a login page  
So that I can use admin dashboard.

- [x] Interface design of login page
- [x] backend development of login page

**Comment by Prasuna-Pokharel** [comment]
**The task is completed 
 Is there  any changes needed ? **
![admin login](https://user-images.githubusercontent.com/80803470/114907737-19eaa800-9e3b-11eb-9e4f-8b65f95d5b3a.jpg)
![login for admin](https://user-images.githubusercontent.com/80803470/114907744-1bb46b80-9e3b-11eb-81b3-d8ff732a0c4c.jpg)

**Comment by sumitkaji** [comment]
Task is completed
this is how login page looks like
![Screenshot (161)](https://user-images.githubusercontent.com/81735853/114979178-20643880-9eaa-11eb-9710-e3301f688a2c.png)
