### ISSUE TITLE
Student dashboard

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/LibraryManagementSystem#8]
As a Student
I want a student dashboard
So that I can reserve books, view books and view reserved books

- [x] Interface design of student dashboard

**Comment by sumitkaji** [comment]
as per the issue raised student can reserve and view books but still some changes is need to be done which we will do in sprint 2
![Screenshot (162)](https://user-images.githubusercontent.com/81735853/114980026-8c936c00-9eab-11eb-8cc6-82444fa06003.png)
